
name: sampledock
channels:
  - pytorch
  - conda-forge
  - bioconda
  - tmap
      
dependencies:
  - python>=3.7
  - pytorch
  - rdkit=2020.9.3
  ## 2020.9.5 has breaking change. 
  - scipy
  - rxdock
  - tmap
  - tqdm
  - faerun
  - mhfp
