name: sampledock
channels:
  - pytorch
  - conda-forge
  - bioconda
  - tmap
      
dependencies:
  - python>=3.7
  - pytorch
  - rdkit>=2021.3.1
  ## 2019.9.5 has breaking change. Fixed in 2021.3.1 and forward
  - scipy
  - rxdock
  - tmap
  - tqdm
  - faerun
  - mhfp
