name: sampledock
channels:
  - pytorch
  - conda-forge
  - bioconda
  - tmap
  - pip
  - pip:
      - faerun
      - mhfp
      
dependencies:
  - python>=3.7
  - pytorch
  - rdkit>=2020.03.3.0
  - scipy
  - rxdock
  - tmap
  - tqdm